project:
  type: website
  output-dir: docs

website:
  title: "Ctrl_S Project Page"
  navbar:
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: Data
        href: data.qmd
      - text: Analysis
        href: analysis.qmd
      - text: analysisss
        href: analysisss.qmd

            
    tools:
      - icon: github
        href: https://github.com/emu-hacettepe-analytics/emu430-fall2023-team-ctrl_s/tree/master

  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "Hacettepe IE - EMU 430 - Fall 2023" 
    border: true
format:
  html:
    toc: true
    toc-location: left
    theme: lux
      # lux
      # simplex
      # sketchy
      # dark: cyborg
    css: styles.css


editor: visual

